version: '2'
services:
    micro-app:
        image: micro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://micro-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    micro-mssql:
        extends:
            file: mssql.yml
            service: micro-mssql
